# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_Config.ipynb.

# %% auto 0
__all__ = ['Config']

# %% ../nbs/01_Config.ipynb 3
import torch
import json
from dataclasses import dataclass, asdict

# %% ../nbs/01_Config.ipynb 4
@dataclass
class Config:
    # Diffusion hyperparameters
    timesteps: int = 1000
    beta1: float = 1e-4
    beta2: float = 0.02

    # Network hyperparameters
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    n_feat: int = 64  # number of hidden dimensions of the feature
    n_cfeat: int = 5  # context vector is of size 5
    height: int = 16  # image size is 16x16
    save_dir: str = "./weights"

    # Training hyperparameters
    batch_size: int = 100
    n_epoch: int = 32
    lrate: float = 1e-3

    def to_json_string(self):
        return json.dumps(asdict(self), indent=4)
