# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_train.ipynb.

# %% auto 0
__all__ = ['construct_noise_schedules']

# %% ../nbs/03_train.ipynb 3
from torch_snippets import *
from .config import Config
from .models import *
from .dataset import *

# %% ../nbs/03_train.ipynb 4
def construct_noise_schedules(config):
    c = config
    t = np.linspace(0, 1, c.timesteps + 1)
    b_t = (c.beta2 - c.beta1) * t + c.beta1
    a_t = 1 - b_t
    ab_t = np.ones(c.timesteps + 1)
    for i in range(1, c.timesteps + 1):
        ab_t[i] = np.exp(np.log(ab_t[i - 1]) + np.log(a_t[i]))
    b_t = (c.beta2 - c.beta1) * torch.linspace(
        0, 1, c.timesteps + 1, device=c.device
    ) + c.beta1
    a_t = 1 - b_t
    ab_t = torch.cumsum(a_t.log(), dim=0).exp()
    ab_t[0] = 1
    return ab_t, a_t, b_t
